DROP SEQUENCE CONTURI_SEQ;
CREATE SEQUENCE CONTURI_SEQ START WITH 2 INCREMENT BY 1;

DROP   TABLE CONTURI;
CREATE TABLE CONTURI (
	 ID INTEGER PRIMARY KEY,
	 USERNAME VARCHAR2(50)  UNIQUE,
	 PAROLA   VARCHAR2(50),
	 EMAIL    VARCHAR2(50),
	 TIP_UTILIZATOR VARCHAR2(20),
         Status Integer,
	 Cod_Activare VARCHAR(20),
   Token        VARCHAR(50)
);
INSERT INTO CONTURI  VALUES(1,'Admin','Root','Admin','Admin',1,'0','0');


DROP   SEQUENCE STUDENTI_SEQ;
CREATE SEQUENCE STUDENTI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE STUDENTI;
CREATE TABLE STUDENTI (
	 ID      INTEGER PRIMARY KEY,
   	 ID_CONT INTEGER,
   	 NR_MATRICOL VARCHAR2(50) UNIQUE,
	 NUME    VARCHAR2(50),
	 PRENUME VARCHAR2(50),
   ID_COMISIE INTEGER,
	 ID_SESIUNE INTEGER
);

DROP   SEQUENCE PROFESORI_SEQ;
CREATE SEQUENCE PROFESORI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE PROFESORI;
CREATE TABLE PROFESORI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 GRAD_DIDACTIC VARCHAR2(20),
   ID_COMISIE INTEGER,
            FUNCTIE_COMISIE VARCHAR2(20)   
);

DROP   SEQUENCE COMISII_SEQ;
CREATE SEQUENCE COMISII_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE COMISII;
CREATE TABLE COMISII (
	 ID       INTEGER,
	 ID_PROF1 INTEGER,
	 ID_PROF2 INTEGER,
	 ID_PROF3 INTEGER,
	 ID_PROF4_DIZERTATIE INTEGER,
	 ID_SECRETAR INTEGER,
	 TIP_COMISIE VARCHAR2(20),
	 SALA        VARCHAR2(20)
);

DROP   SEQUENCE SESIUNI_SEQ;
CREATE SEQUENCE SESIUNI_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE   SESIUNI;
CREATE TABLE SESIUNI (
	 ID     INTEGER PRIMARY KEY,
	 INCEPUT_SESIUNE TIMESTAMP,
	 SFARSIT_SESIUNE TIMESTAMP,
   Active INTEGER
);

DROP   SEQUENCE MESAJE_SEQ;
CREATE SEQUENCE MESAJE_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE  MESAJE;
CREATE TABLE  MESAJE (
	 ID            INTEGER,
	 ID_EMITATOR   INTEGER,
	 ID_DESTINATAR INTEGER,
	 MESAJ         VARCHAR(1000)
);

DROP   SEQUENCE LICENTE_SEQ;
CREATE SEQUENCE LICENTE_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE LICENTE;
CREATE TABLE LICENTE (
	ID  INTEGER PRIMARY KEY,
	TITLU VARCHAR(50),
        ID_PROFESOR INTEGER,
	ID_STUDENT  INTEGER,
	MATERIALE_LICENTA VARCHAR(1000),
	ID_SESIUNE  INTEGER,
  TIP  VARCHAR2(50),
  FISIER BLOB
);

DROP   SEQUENCE DETALII_SEQ;
CREATE SEQUENCE DETALII_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE DETALII_LICENTE;
CREATE TABLE DETALII_LICENTE (
	 ID INTEGER PRIMARY KEY,
         ID_COMISIE  INTEGER,
	 NOTA_1_ORAL  INTEGER,
	 NOTA_1_PROIECT INTEGER,
	 NOTA_2_ORAL INTEGER,
	 NOTA_2_PROIECT INTEGER,
	 NOTA_3_ORAL INTEGER,
	 NOTA_3_PROIECT INTEGER,
	 NOTA_4_ORAL_DIZERTATIE INTEGER,
	 NOTA_4_PROIECT_DIZERTATIE INTEGER,
   NOTA_5_ORAL_COORDONATOR INTEGER,
   NOTA_5_PROIECT_COORDONATOR INTEGER,
	 DATA_ORA_SUSTINERE TIMESTAMP
);

commit;

INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(1,'Alboaie','Lenuta','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(2,'Arusoaie','Andreea','Asist. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(3,'Arusoaie','Andrei','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(4,'Asimioanei','Ion','Lect.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(5,'Benchea','Razvan','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(6,'Birjoveanu','Catalin','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(7,'Breaban','Mihaela','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(8,'Buraga','Sabin','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(9,'Captarencu','Oana','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(10,'Ciobaca','Stefan','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(11,'Ciortuz','Liviu','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(12,'Cristea','Dan','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(13,'Croitoru','Cornelius','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(14,'Forascu','Corina','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(15,'Frasinaru','Cristian','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(16,'Gatu','Cristian','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(17,'Gabrilut','Dragos','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(18,'Ghirvu','Lucian','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(19,'Grigoras','Gheorghe','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(20,'Iacob','Florin','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(21,'Iftene','Adrian','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(22,'Iftene','Sorin','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(23,'Ignat','Anca','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(24,'Lucanu','Dorel','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(25,'Luchian','Henri','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(26,'Masalagiu','Cristian','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(27,'Moruz','Alex','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(28,'Olariu','Florentin','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(29,'Onica','Emanuel','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(30,'Onofrei','Paula','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(31,'Oprea','Dumitru','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(32,'Patrut','Bogdan','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(33,'Pistol','Ionut','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(34,'Radulescu','Vlad','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(35,'Teodorescu','Horia','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(36,'Tiplea','Ferucio','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(37,'Trandabat','Diana','Conf. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(38,'Varlan','Cosmin','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(39,'Vidrascu','Cristian','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(40,'Vitcu','Anca','Conf. Dr.');

commit;

INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'ionescu.mircea','parola','ionescu.mircea@info.uaic.ro','Student',1,'blabla','token1');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'polonescu.mia','parola','polonescu.mia@info.uaic.ro','Student',1,'blabla','token2');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'agapei.ioana','parola','agapei.ioana@info.uaic.ro','Student',1,'blabla','token3');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'stanescu.mihai','parola','stanescu.mihai@info.uaic.ro','Student',1,'blabla','token4');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'mardare.radu','parola','mardare.radu@info.uaic.ro','Student',1,'blabla','token5');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'lupu.irina','parola','lupu.irina@info.uaic.ro','Student',1,'blabla','token6');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'lupascu.mioara','parola','lupascu.mioara@info.uaic.ro','Student',1,'blabla','token7');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'cristea.irina','parola','cristea.irina@info.uaic.ro','Student',1,'blabla','token8');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'jimmy.grigory','parola','jimmy.grygory@info.uaic.ro','Student',1,'blabla','token9');

INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,2,'sv3456781','Ionescu','Mirecea',1,1);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,3,'sv3456782','Polonescu','Mia',1,1);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,4,'sv3456783','Agapei','Ioana',1,2);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,5,'sv3456784','Stanescu','Mihai',1,3);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,6,'sv3456785','Mardare','Radu',1,4);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,7,'sv3456786','Lupu','Irina',1,1);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,8,'sv3456787','Lupascu','Mioara',1,3);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,9,'sv3456788','Cristea','Irina',1,4);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,10,'sv3456789','Jimmy','Grygory',1,1);


Update PROFESORI SET ID_COMISIE=1,FUNCTIE_COMISIE='Presedinte' where id=1;
Update PROFESORI SET ID_COMISIE=1,FUNCTIE_COMISIE='Secretar' where id=2;
Update PROFESORI SET ID_COMISIE=1,FUNCTIE_COMISIE='Evaluator' where id=3;
Update PROFESORI SET ID_COMISIE=2,FUNCTIE_COMISIE='Presedinte' where id=5;
Update PROFESORI SET ID_COMISIE=2,FUNCTIE_COMISIE='Secretar' where id=6;
Update PROFESORI SET ID_COMISIE=2,FUNCTIE_COMISIE='Evaluator' where id=7;
Update PROFESORI SET ID_COMISIE=3,FUNCTIE_COMISIE='Presedinte' where id=9;
Update PROFESORI SET ID_COMISIE=3,FUNCTIE_COMISIE='Secretar' where id=10;
Update PROFESORI SET ID_COMISIE=3,FUNCTIE_COMISIE='Evaluator' where id=11;
Update PROFESORI SET ID_COMISIE=4,FUNCTIE_COMISIE='Presedinte' where id=13;
Update PROFESORI SET ID_COMISIE=4,FUNCTIE_COMISIE='Secretar' where id=14;
Update PROFESORI SET ID_COMISIE=4,FUNCTIE_COMISIE='Evaluator' where id=15;
Update PROFESORI SET ID_COMISIE=4,FUNCTIE_COMISIE='Evaluator' where id=16;


INSERT INTO COMISII VALUES(COMISII_SEQ.NEXTVAL,1,2,3,null,2,'licenta','307');
INSERT INTO COMISII VALUES(COMISII_SEQ.NEXTVAL,5,6,7,null,6,'licenta','308');
INSERT INTO COMISII VALUES(COMISII_SEQ.NEXTVAL,9,10,11,null,10,'dizertatie','309');
INSERT INTO COMISII VALUES(COMISII_SEQ.NEXTVAL,13,14,15,16,14,'dizertatie','407');


INSERT INTO SESIUNI VALUES(SESIUNI_SEQ.NEXTVAL,TO_DATE( '01-07-2018','dd-mm-yyyy'),TO_DATE( '01-08-2018','dd-mm-yyyy'),1);

INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta1',2,1,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta2',5,2,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta3',3,3,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta4',1,4,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta5',3,5,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta6',6,6,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta7',4,7,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta8',7,8,'www.google.ro',1,'LICENTA','');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'licenta9',38,9,'wwww.google.ro',1,'LICENTA','');

INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,1,5,5,5,5,5,5,NULL,NULL,NULL,NULL,TO_TIMESTAMP('1-JUL-17 10:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,2,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('1-JUL-17 12:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,2,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('2-JUL-17 12:30:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,3,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('4-JUL-17 13:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,4,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('5-JUL-17 12:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,1,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('2-JUL-17 14:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,2,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('6-JUL-17 12:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,3,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('3-JUL-17 12:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,1,5,5,5,5,5,5,NULL,NULL,5,5,TO_TIMESTAMP('8-JUL-17 14:00:00','DD-Mon-RR HH24:MI:SS'));

commit;
DECLARE
  rezultat INTEGER;
BEGIN
  rezultat:=INREGISTRARE_PROF('lenuta.alboaie','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('andreea.arusoaie','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('andrei.arusoaie','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('razvan.benchea','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('catalin.birjoveanu','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('mihaela.breaban','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('oana.captarencu','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('stefan.ciobaca','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('liviu.ciortuz','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('cornelius.croitoru','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('corina.forascu','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('cristian.frasinaru','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  rezultat:=INREGISTRARE_PROF('cristian.gatu','parola');
  DBMS_OUTPUT.PUT_LINE(rezultat);
  
END;



--COOOOMIT HERE
