DROP   SEQUENCE CONTURI_SEQ;
CREATE SEQUENCE CONTURI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE CONTURI;
CREATE TABLE CONTURI (
	 ID INTEGER PRIMARY KEY,
	 USERNAME VARCHAR2(30)  UNIQUE,
	 PAROLA   VARCHAR2(30),
	 EMAIL    VARCHAR2(30)  UNIQUE,
	 TIP_UTILIZATOR VARCHAR2(20),
   VERIFICAT INTEGER
);

DROP   TABLE STUDENTI;
CREATE TABLE STUDENTI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
   NR_MATRICOL VARCHAR2(20) UNIQUE,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 PROMOTIA VARCHAR(20)
);

DROP   TABLE PROFESORI;
CREATE TABLE PROFESORI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 GRAD_DIDACTIC VARCHAR2(20),
   ID_COMISIE INTEGER,
   FUNCTIE_COMISIE VARCHAR2(20)   
);

DROP TABLE COMISII;
CREATE TABLE COMISII (
	 ID       INTEGER,
	 ID_PROF1 INTEGER,
	 ID_PROF2 INTEGER,
	 ID_PROF3 INTEGER,
	 ID_PROF4_DIZERTATIE INTEGER,
	 ID_SECRETAR INTEGER,
	 TIP_COMISIE VARCHAR2(20),
	 ID_EVALUARE INTEGER
);

DROP   TABLE  INTERVAL_EVALUARE;
CREATE TABLE  INTERVAL_EVALUARE (
	 ID         INTEGER,
	 ID_SESIUNE INTEGER,
	 ID_COMISIE INTEGER,
	 INCEPUT_EVALUARE DATE,
   SFARSIT_EVALUARE DATE
);

DROP TABLE   SESIUNI;
CREATE TABLE SESIUNI (
	 ID     INTEGER PRIMARY KEY,
	 INCEPUT_SESIUNE DATE,
	 SFARSIT_SESIUNE DATE
);


DROP   TABLE  MESAJE;
CREATE TABLE  MESAJE (
	 ID            INTEGER,
	 ID_EMITATOR   INTEGER,
	 ID_DESTINATAR INTEGER,
	 MESAJ         VARCHAR(500)
);


DROP   TABLE LICENTE;
CREATE TABLE LICENTE (
	ID_LICENTA  INTEGER PRIMARY KEY,
  ID_PROFESOR INTEGER,
	ID_STUDENT  INTEGER,
	ID_SESIUNE  INTEGER
);

DROP TABLE DETALII_LICENTE;
CREATE TABLE DETALII_LICENTE (
	 ID_LICENTA INTEGER PRIMARY KEY,
   TITLU      VARCHAR(20),
   MATERIALE_LINK VARCHAR(50),
   ID_COMISIE  INTEGER,
	 NOTA_1_ORAL  INTEGER,
	 NOTA_1_PROIECT INTEGER,
	 NOTA_2_ORAL INTEGER,
	 NOTA_2_PROIECT INTEGER,
	 NOTA_3_ORAL INTEGER,
	 NOTA_3_PROIECT INTEGER,
	 NOTA_4_ORAL INTEGER,
	 NOTA_4_PROIECT INTEGER,
	 NOTA_FINALA_ORAL INTEGER,
   NOTA_FINALA_PROIECT INTEGER,
	 NOTA_FINALA INTEGER,
	 DATA_SUSTINERE DATE,
	 INTERVAL_ORAR VARCHAR2(20)
);

DROP TABLE VERIFICARE;
CREATE TABLE VERIFICARE(
  COD_VERIFICARE VARCHAR2(20),
  ID_CONT        INTEGER
)




