DROP SEQUENCE CONTURI_SEQ;
CREATE SEQUENCE CONTURI_SEQ START WITH 2 INCREMENT BY 1;

DROP   TABLE CONTURI;
CREATE TABLE CONTURI (
	 ID INTEGER PRIMARY KEY,
	 USERNAME VARCHAR2(50)  UNIQUE,
	 PAROLA   VARCHAR2(50),
	 EMAIL    VARCHAR2(50),
	 TIP_UTILIZATOR VARCHAR2(20),
         Status Integer,
	 Cod_Activare VARCHAR(20),
   Token        VARCHAR(50)
);
INSERT INTO CONTURI  VALUES(1,'Admin','Root','Admin','Admin',1,'0','0');


DROP   SEQUENCE STUDENTI_SEQ;
CREATE SEQUENCE STUDENTI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE STUDENTI;
CREATE TABLE STUDENTI (
	 ID      INTEGER PRIMARY KEY,
   	 ID_CONT INTEGER,
   	 NR_MATRICOL VARCHAR2(50) UNIQUE,
	 NUME    VARCHAR2(50),
	 PRENUME VARCHAR2(50),
   ID_COMISIE INTEGER,
	 ID_SESIUNE INTEGER
);

DROP   SEQUENCE PROFESORI_SEQ;
CREATE SEQUENCE PROFESORI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE PROFESORI;
CREATE TABLE PROFESORI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 GRAD_DIDACTIC VARCHAR2(20),
   ID_COMISIE INTEGER,
            FUNCTIE_COMISIE VARCHAR2(20)   
);

DROP   SEQUENCE COMISII_SEQ;
CREATE SEQUENCE COMISII_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE COMISII;
CREATE TABLE COMISII (
	 ID       INTEGER,
	 ID_PROF1 INTEGER,
	 ID_PROF2 INTEGER,
	 ID_PROF3 INTEGER,
	 ID_PROF4_DIZERTATIE INTEGER,
	 ID_SECRETAR INTEGER,
	 TIP_COMISIE VARCHAR2(20),
	 SALA        VARCHAR2(20)
);

DROP   SEQUENCE SESIUNI_SEQ;
CREATE SEQUENCE SESIUNI_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE   SESIUNI;
CREATE TABLE SESIUNI (
	 ID     INTEGER PRIMARY KEY,
	 INCEPUT_SESIUNE TIMESTAMP,
	 SFARSIT_SESIUNE TIMESTAMP
);

DROP   SEQUENCE MESAJE_SEQ;
CREATE SEQUENCE MESAJE_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE  MESAJE;
CREATE TABLE  MESAJE (
	 ID            INTEGER,
	 ID_EMITATOR   INTEGER,
	 ID_DESTINATAR INTEGER,
	 MESAJ         VARCHAR(1000)
);

DROP   SEQUENCE LICENTE_SEQ;
CREATE SEQUENCE LICENTE_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE LICENTE;
CREATE TABLE LICENTE (
	ID  INTEGER PRIMARY KEY,
	TITLU VARCHAR(50),
        ID_PROFESOR INTEGER,
	ID_STUDENT  INTEGER,
	MATERIALE_LICENTA VARCHAR(1000),
	ID_SESIUNE  INTEGER,
  TIP  VARCHAR2(50)
);

DROP   SEQUENCE DETALII_SEQ;
CREATE SEQUENCE DETALII_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE DETALII_LICENTE;
CREATE TABLE DETALII_LICENTE (
	 ID INTEGER PRIMARY KEY,
         ID_COMISIE  INTEGER,
	 NOTA_1_ORAL  INTEGER,
	 NOTA_1_PROIECT INTEGER,
	 NOTA_2_ORAL INTEGER,
	 NOTA_2_PROIECT INTEGER,
	 NOTA_3_ORAL INTEGER,
	 NOTA_3_PROIECT INTEGER,
	 NOTA_4_ORAL_DIZERTATIE INTEGER,
	 NOTA_4_PROIECT_DIZERTATIE INTEGER,
   NOTA_5_ORAL_COORDONATOR INTEGER,
   NOTA_5_PROIECT_COORDONATOR INTEGER,
	 DATA_ORA_SUSTINERE TIMESTAMP
);



