INSERT INTO CONTURI  VALUES(2,'jimmy.jimmy','jimmy','jimmy.jimmy@info.uaic.ro','Student',1);
ALTER SEQUENCE CONTURI_SEQ INCREMENT BY 1;
INSERT INTO CONTURI  VALUES(3,'grigory.grigory','grigory','grigory.grygory@info.uaic.ro','Student',0);
ALTER SEQUENCE CONTURI_SEQ INCREMENT BY 1;

INSERT INTO STUDENTI VALUES(1,2,'nr_matricol_jimmy','jimmy','jimmy','2018');
ALTER SEQUENCE STUDENTI_SEQ INCREMENT BY 1;
INSERT INTO STUDENTI VALUES(2,3,'nr_matricol_grigory','grigory','grigory','2018');
ALTER SEQUENCE STUDENTI_SEQ INCREMENT BY 1;

INSERT INTO COMISII VALUES(1,1,2,3,4,1,'licenta',1);
ALTER SEQUENCE COMISII_SEQ INCREMENT BY 1;
INSERT INTO COMISII VALUES(2,1,2,3,4,1,'dizertatie',1);
ALTER SEQUENCE COMISII_SEQ INCREMENT BY 1;

INSERT INTO SESIUNI VALUES(1,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '01-02-2018','dd-mm-yyyy'));
ALTER SEQUENCE SESIUNI_SEQ INCREMENT BY 1;

INSERT INTO EVALUARI VALUES(1,1,1,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '03-01-2018','dd-mm-yyyy'));
ALTER SEQUENCE EVALUARI_SEQ INCREMENT BY 1;
INSERT INTO EVALUARI VALUES(2,1,2,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '03-01-2018','dd-mm-yyyy'));
ALTER SEQUENCE EVALUARI_SEQ INCREMENT BY 1;

INSERT INTO MESAJE VALUES(1,2,3,'hey Grigory, sunt eu Jimmy');
ALTER SEQUENCE MESAJE_SEQ INCREMENT BY 1;
INSERT INTO MESAJE VALUES(2,3,2,'Go home Jimmy');
ALTER SEQUENCE MESAJE_SEQ INCREMENT BY 1;

INSERT INTO LICENTE VALUES(1,'Licenta lui Jimmy',1,1,'https://www.google.ro/search?q=jimmy',1);
ALTER SEQUENCE LICENTE_SEQ INCREMENT BY 1;
INSERT INTO LICENTE VALUES(2,'Licenta lui Grigory',1,2,'https://www.google.ro/search?q=grigory',1);
ALTER SEQUENCE LICENTE_SEQ INCREMENT BY 1;

INSERT INTO DETALII_LICENTE VALUES(1,1,5,5,5,5,5,5,5,5,TO_TIMESTAMP('10-SEP-17 12:00:00','DD-Mon-RR HH24:MI:SS'));
ALTER SEQUENCE DETALII_SEQ INCREMENT BY 1;
INSERT INTO DETALII_LICENTE VALUES(2,1,5,5,5,5,5,5,5,5,TO_TIMESTAMP('01-01-2018 12:30:00','dd-mm-yyyy HH24:MI:SS'));
ALTER SEQUENCE DETALII_SEQ INCREMENT BY 1;

