DROP   SEQUENCE CONTURI_SEQ;
CREATE SEQUENCE CONTURI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE CONTURI;
CREATE TABLE CONTURI (
	 ID INTEGER PRIMARY KEY,
	 USERNAME VARCHAR2(30)  UNIQUE,
	 PAROLA   VARCHAR2(30),
	 EMAIL    VARCHAR2(30)  UNIQUE,
	 TIP_UTILIZATOR VARCHAR2(20),
         VERIFICAT INTEGER
);

DROP   TABLE STUDENTI;
CREATE TABLE STUDENTI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
   NR_MATRICOL VARCHAR2(20) UNIQUE,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 PROMOTIA VARCHAR(20)
);

DROP   TABLE PROFESORI;
CREATE TABLE PROFESORI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 GRAD_DIDACTIC VARCHAR2(20),
   ID_COMISIE INTEGER,
   FUNCTIE_COMISIE VARCHAR2(20)   
);

DROP TABLE COMISII;
CREATE TABLE COMISII (
	 ID       INTEGER,
	 ID_PROF1 INTEGER,
	 ID_PROF2 INTEGER,
	 ID_PROF3 INTEGER,
	 ID_PROF4_DIZERTATIE INTEGER,
	 ID_SECRETAR INTEGER,
	 TIP_COMISIE VARCHAR2(20),
	 ID_EVALUARE INTEGER
);

DROP   TABLE  INTERVAL_EVALUARE;
CREATE TABLE  INTERVAL_EVALUARE (
	 ID         INTEGER,
	 ID_SESIUNE INTEGER,
	 ID_COMISIE INTEGER,
	 INCEPUT_EVALUARE DATE,
   SFARSIT_EVALUARE DATE
);

DROP TABLE   SESIUNI;
CREATE TABLE SESIUNI (
	 ID     INTEGER PRIMARY KEY,
	 INCEPUT_SESIUNE DATE,
	 SFARSIT_SESIUNE DATE
);


DROP   TABLE  MESAJE;
CREATE TABLE  MESAJE (
	 ID            INTEGER,
	 ID_EMITATOR   INTEGER,
	 ID_DESTINATAR INTEGER,
	 MESAJ         VARCHAR(500)
);


DROP   TABLE LICENTE;
CREATE TABLE LICENTE (
	ID_LICENTA  INTEGER PRIMARY KEY,
  ID_PROFESOR INTEGER,
	ID_STUDENT  INTEGER,
	ID_SESIUNE  INTEGER
);

DROP TABLE DETALII_LICENTE;
CREATE TABLE DETALII_LICENTE (
	 ID_LICENTA INTEGER PRIMARY KEY,
   TITLU      VARCHAR(20),
   MATERIALE_LINK VARCHAR(50),
   ID_COMISIE  INTEGER,
	 NOTA_1_ORAL  INTEGER,
	 NOTA_1_PROIECT INTEGER,
	 NOTA_2_ORAL INTEGER,
	 NOTA_2_PROIECT INTEGER,
	 NOTA_3_ORAL INTEGER,
	 NOTA_3_PROIECT INTEGER,
	 NOTA_4_ORAL INTEGER,
	 NOTA_4_PROIECT INTEGER,
	 NOTA_FINALA_ORAL INTEGER,
   NOTA_FINALA_PROIECT INTEGER,
	 NOTA_FINALA INTEGER,
	 DATA_SUSTINERE DATE,
	 INTERVAL_ORAR VARCHAR2(20)
);

DROP TABLE VERIFICARE;
CREATE TABLE VERIFICARE(
  COD_VERIFICARE VARCHAR2(20),
  ID_CONT        INTEGER
);

INSERT INTO CONTURI  VALUES(1,'Admin','Root','Admin','Admin',1);
INSERT INTO CONTURI  VALUES(2,'jimmy.jimmy','jimmy','jimmy.jimmy@info.uaic.ro','Student',1);
INSERT INTO CONTURI  VALUES(3,'grigory.grigory','grigory','grigory.grygory@info.uaic.ro','Student',0);

INSERT INTO STUDENTI VALUES(1,2,'nr_matricol_jimmy','jimmy','jimmy','2018');
INSERT INTO STUDENTI VALUES(2,3,'nr_matricol_grigory','grigory','grigory','2018');

INSERT INTO COMISII VALUES(1,1,2,3,4,1,'licenta',1);
INSERT INTO COMISII VALUES(2,1,2,3,4,1,'dizertatie',1);

INSERT INTO SESIUNI VALUES(1,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '01-02-2018','dd-mm-yyyy'));

INSERT INTO INTERVAL_EVALUARE VALUES(1,1,1,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '03-01-2018','dd-mm-yyyy'));
INSERT INTO INTERVAL_EVALUARE VALUES(2,1,2,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '03-01-2018','dd-mm-yyyy'));

INSERT INTO MESAJE VALUES(1,2,3,'hey Grigory, sunt eu Jimmy');
INSERT INTO MESAJE VALUES(2,3,2,'Go home Jimmy');

INSERT INTO LICENTE VALUES(1,1,1,1);
INSERT INTO LICENTE VALUES(2,1,2,1);

INSERT INTO DETALII_LICENTE VALUES(1,'Licenta lui Jimmy','https://www.google.ro/search?q=jimmy',1,5,5,5,5,5,5,5,5,5,5,5,TO_DATE( '01-01-2018','dd-mm-yyyy'),'12:00-12:20');
INSERT INTO DETALII_LICENTE VALUES(2,'Licenta lui Grigory','https://www.google.ro/search?q=grigory',1,5,5,5,5,5,5,5,5,5,5,5,TO_DATE( '01-01-2018','dd-mm-yyyy'),'12:30-12:50');

INSERT INTO VERIFICARE VALUES('00000000000000000000',3);

INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(1,'ALBOAIE','LENUTA','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(2,'ARUSOAIE','ANDREEA','Asist. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(3,'ARUSOAIE','ANDREI','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(4,'ASIMIOANEI','ION','Lect.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(5,'BENCHEA','RAZVAN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(6,'BIRJOVEANU','CATALIN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(7,'BREABAN','MIHAELA','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(8,'BURAGA','SABIN CORNELIU','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(9,'CAPTARENCU','OANA','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(10,'CIOBACA','STEFAN','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(11,'CIORTUZ','LIVIU','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(12,'CRISTEA','DAN','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(13,'CROITORU','CORNELIUS','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(14,'FORASCU','CORINA','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(15,'FRASINARU','CRISTIAN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(16,'GATU','CRISTIAN','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(17,'GAVRILUT','DRAGOS','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(18,'GHIRVU','LUCIAN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(19,'GRIGORAS','GHEORGHE','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(20,'IACOB','FLORIN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(21,'IFTENE','ADRIAN','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(22,'IFTENE','SORIN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(23,'IGNAT','ANCA','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(24,'LUCANU','DOREL','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(25,'LUCHIAN','HENRI','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(26,'MASALAGIU','CRISTIAN','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(27,'MORUZ','ALEX','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(28,'OLARIU','FLORENTIN EMANUEL','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(29,'ONICA','EMANUEL','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(30,'ONOFREI','PAULA','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(31,'OPREA','DUMITRU','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(32,'PATRUT','BOGDAN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(33,'PISTOL','IONUT','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(34,'RADULESCU','VLAD','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(35,'TEODORESCU','HORIA','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(36,'TIPLEA','FERUCIO LAURENTIU','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(37,'TRANDABAT','DIANA','Conf. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(38,'VARLAN','COSMIN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(39,'VIDRASCU','CRISTIAN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(40,'VITCU','ANCA','Conf. Dr.');

commit;


