DROP SEQUENCE CONTURI_SEQ;
CREATE SEQUENCE CONTURI_SEQ START WITH 2 INCREMENT BY 1;

DROP   TABLE CONTURI;
CREATE TABLE CONTURI (
	 ID INTEGER PRIMARY KEY,
	 USERNAME VARCHAR2(50)  UNIQUE,
	 PAROLA   VARCHAR2(50),
	 EMAIL    VARCHAR2(50),
	 TIP_UTILIZATOR VARCHAR2(20),
         Status Integer,
	 Cod_Activare VARCHAR(20),
   Token        VARCHAR(50)
);
INSERT INTO CONTURI  VALUES(1,'Admin','Root','Admin','Admin',1,'0','0');


DROP   SEQUENCE STUDENTI_SEQ;
CREATE SEQUENCE STUDENTI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE STUDENTI;
CREATE TABLE STUDENTI (
	 ID      INTEGER PRIMARY KEY,
   	 ID_CONT INTEGER,
   	 NR_MATRICOL VARCHAR2(50) UNIQUE,
	 NUME    VARCHAR2(50),
	 PRENUME VARCHAR2(50),
   ID_COMISIE INTEGER,
	 ID_SESIUNE INTEGER
);

DROP   SEQUENCE PROFESORI_SEQ;
CREATE SEQUENCE PROFESORI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE PROFESORI;
CREATE TABLE PROFESORI (
	 ID      INTEGER PRIMARY KEY,
   ID_CONT INTEGER,
	 NUME    VARCHAR2(20),
	 PRENUME VARCHAR2(20),
	 GRAD_DIDACTIC VARCHAR2(20),
   ID_COMISIE INTEGER,
            FUNCTIE_COMISIE VARCHAR2(20)   
);

DROP   SEQUENCE COMISII_SEQ;
CREATE SEQUENCE COMISII_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE COMISII;
CREATE TABLE COMISII (
	 ID       INTEGER,
	 ID_PROF1 INTEGER,
	 ID_PROF2 INTEGER,
	 ID_PROF3 INTEGER,
	 ID_PROF4_DIZERTATIE INTEGER,
	 ID_SECRETAR INTEGER,
	 TIP_COMISIE VARCHAR2(20),
	 ID_EVALUARE INTEGER
);

DROP   SEQUENCE EVALUARI_SEQ;
CREATE SEQUENCE EVALUARI_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE  EVALUARI;
CREATE TABLE  EVALUARI (
	 ID         INTEGER,
	 ID_SESIUNE INTEGER,
	 ID_COMISIE INTEGER,
	 INCEPUT_EVALUARE TIMESTAMP,
   SFARSIT_EVALUARE TIMESTAMP,
   SALA       VARCHAR2(50)
);

DROP   SEQUENCE SESIUNI_SEQ;
CREATE SEQUENCE SESIUNI_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE   SESIUNI;
CREATE TABLE SESIUNI (
	 ID     INTEGER PRIMARY KEY,
	 INCEPUT_SESIUNE TIMESTAMP,
	 SFARSIT_SESIUNE TIMESTAMP
);

DROP   SEQUENCE MESAJE_SEQ;
CREATE SEQUENCE MESAJE_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE  MESAJE;
CREATE TABLE  MESAJE (
	 ID            INTEGER,
	 ID_EMITATOR   INTEGER,
	 ID_DESTINATAR INTEGER,
	 MESAJ         VARCHAR(1000)
);

DROP   SEQUENCE LICENTE_SEQ;
CREATE SEQUENCE LICENTE_SEQ START WITH 1 INCREMENT BY 1;

DROP   TABLE LICENTE;
CREATE TABLE LICENTE (
	ID  INTEGER PRIMARY KEY,
	TITLU VARCHAR(50),
        ID_PROFESOR INTEGER,
	ID_STUDENT  INTEGER,
	MATERIALE_LICENTA VARCHAR(1000),
	ID_SESIUNE  INTEGER,
  TIP  VARCHAR2(50)
);

DROP   SEQUENCE DETALII_SEQ;
CREATE SEQUENCE DETALII_SEQ START WITH 1 INCREMENT BY 1;

DROP TABLE DETALII_LICENTE;
CREATE TABLE DETALII_LICENTE (
	 ID INTEGER PRIMARY KEY,
         ID_COMISIE  INTEGER,
	 NOTA_1_ORAL  INTEGER,
	 NOTA_1_PROIECT INTEGER,
	 NOTA_2_ORAL INTEGER,
	 NOTA_2_PROIECT INTEGER,
	 NOTA_3_ORAL INTEGER,
	 NOTA_3_PROIECT INTEGER,
	 NOTA_4_ORAL_DIZERTATIE INTEGER,
	 NOTA_4_PROIECT_DIZERTATIE INTEGER,
   NOTA_5_ORAL_COORDONATOR INTEGER,
   NOTA_5_PROIECT_COORDONATOR INTEGER,
	 DATA_ORA_SUSTINERE TIMESTAMP
);



INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'jimmy.jimmy','jimmy','jimmy.jimmy@info.uaic.ro','Student',1,'fsdagfsdg','0');
INSERT INTO CONTURI  VALUES(CONTURI_SEQ.NEXTVAL,'grigory.grigory','grigory','grigory.grygory@info.uaic.ro','Student',0,'safasfasf','0');

INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,2,'nr_matricol_jimmy','jimmy','jimmy',1,1);
INSERT INTO STUDENTI VALUES(STUDENTI_SEQ.NEXTVAL,3,'nr_matricol_grigory','grigory','grigory',1,1);

INSERT INTO COMISII VALUES(COMISII_SEQ.NEXTVAL,1,2,3,4,1,'licenta',1);
INSERT INTO COMISII VALUES(COMISII_SEQ.NEXTVAL,1,2,3,4,1,'dizertatie',1);

INSERT INTO SESIUNI VALUES(SESIUNI_SEQ.NEXTVAL,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '01-02-2018','dd-mm-yyyy'));

INSERT INTO EVALUARI VALUES(EVALUARI_SEQ.NEXTVAL,1,1,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '03-01-2018','dd-mm-yyyy'),'C302');
INSERT INTO EVALUARI VALUES(EVALUARI_SEQ.NEXTVAL,1,2,TO_DATE( '01-01-2018','dd-mm-yyyy'),TO_DATE( '03-01-2018','dd-mm-yyyy'),'C301');

INSERT INTO MESAJE VALUES(MESAJE_SEQ.NEXTVAL,2,3,'hey Grigory, sunt eu Jimmy');
INSERT INTO MESAJE VALUES(MESAJE_SEQ.NEXTVAL,3,2,'Go home Jimmy');

INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'Licenta lui Jimmy',1,1,'https://www.google.ro/search?q=jimmy',1,'Licenta');
INSERT INTO LICENTE VALUES(LICENTE_SEQ.NEXTVAL,'Licenta lui Grigory',1,2,'https://www.google.ro/search?q=grigory',1,'Dizertatie');

INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,1,5,5,5,5,5,5,5,5,5,5,TO_TIMESTAMP('10-SEP-17 12:00:00','DD-Mon-RR HH24:MI:SS'));
INSERT INTO DETALII_LICENTE VALUES(DETALII_SEQ.NEXTVAL,1,5,5,5,5,5,5,5,5,5,5,TO_TIMESTAMP('01-01-2018 12:30:00','dd-mm-yyyy HH24:MI:SS'));

INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(1,'ALBOAIE','LENUTA','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(2,'ARUSOAIE','ANDREEA','Asist. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(3,'ARUSOAIE','ANDREI','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(4,'ASIMIOANEI','ION','Lect.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(5,'BENCHEA','RAZVAN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(6,'BIRJOVEANU','CATALIN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(7,'BREABAN','MIHAELA','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(8,'BURAGA','SABIN CORNELIU','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(9,'CAPTARENCU','OANA','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(10,'CIOBACA','STEFAN','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(11,'CIORTUZ','LIVIU','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(12,'CRISTEA','DAN','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(13,'CROITORU','CORNELIUS','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(14,'FORASCU','CORINA','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(15,'FRASINARU','CRISTIAN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(16,'GATU','CRISTIAN','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(17,'GAVRILUT','DRAGOS','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(18,'GHIRVU','LUCIAN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(19,'GRIGORAS','GHEORGHE','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(20,'IACOB','FLORIN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(21,'IFTENE','ADRIAN','Conf. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(22,'IFTENE','SORIN','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(23,'IGNAT','ANCA','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(24,'LUCANU','DOREL','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(25,'LUCHIAN','HENRI','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(26,'MASALAGIU','CRISTIAN','Prof. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(27,'MORUZ','ALEX','Lect. DR.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(28,'OLARIU','FLORENTIN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(29,'ONICA','EMANUEL','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(30,'ONOFREI','PAULA','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(31,'OPREA','DUMITRU','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(32,'PATRUT','BOGDAN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(33,'PISTOL','IONUT','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(34,'RADULESCU','VLAD','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(35,'TEODORESCU','HORIA','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(36,'TIPLEA','FERUCIO','Prof. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(37,'TRANDABAT','DIANA','Conf. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(38,'VARLAN','COSMIN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(39,'VIDRASCU','CRISTIAN','Lect. Dr.');
INSERT INTO PROFESORI(ID,NUME,PRENUME,GRAD_DIDACTIC) VALUES(40,'VITCU','ANCA','Conf. Dr.');

commit;